[package]
name = "data-onion"
version = "0.1.0"
authors = ["Marc Noirot <marc.noirot@gmail.com>"]
edition = "2021"

[dependencies]
aes = "0.8.2"
bitvec = "1.0.1"
byteorder = "1.3.4"
ctr = "0.9.2"
ecb = { version = "0.1.1", features = ["std"] }
nom = "7.1.1"
packet = "0.1.3"
